version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1111
      - DB_NAME=db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
